# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from MillerRabinPrimeTest import *
from FastExponentation import *
from ExtendedEuclidean import *
from ChineseRemainder import *


class Ui_RSA(object):
    def setupUi(self, RSA):
        RSA.setObjectName("RSA")
        RSA.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=RSA)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 611, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pPrime_Label = QtWidgets.QLabel(parent=self.groupBox)
        self.pPrime_Label.setGeometry(QtCore.QRect(10, 40, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pPrime_Label.setFont(font)
        self.pPrime_Label.setObjectName("pPrime_Label")
        self.qPrime_Label = QtWidgets.QLabel(parent=self.groupBox)
        self.qPrime_Label.setGeometry(QtCore.QRect(10, 100, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.qPrime_Label.setFont(font)
        self.qPrime_Label.setObjectName("qPrime_Label")
        self.pInput_Box = QtWidgets.QTextEdit(parent=self.groupBox)
        self.pInput_Box.setGeometry(QtCore.QRect(350, 40, 151, 51))
        self.pInput_Box.setObjectName("pInput_Box")
        self.qInput_Box = QtWidgets.QTextEdit(parent=self.groupBox)
        self.qInput_Box.setGeometry(QtCore.QRect(350, 100, 151, 51))
        self.qInput_Box.setObjectName("qInput_Box")
        self.pGenerate_Prime = QtWidgets.QPushButton(parent=self.groupBox)
        self.pGenerate_Prime.setGeometry(QtCore.QRect(510, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pGenerate_Prime.setFont(font)
        self.pGenerate_Prime.setObjectName("pGenerate_Prime")
        self.qGenerate_Prime = QtWidgets.QPushButton(parent=self.groupBox)
        self.qGenerate_Prime.setGeometry(QtCore.QRect(510, 100, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.qGenerate_Prime.setFont(font)
        self.qGenerate_Prime.setObjectName("qGenerate_Prime")
        RSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        RSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RSA)
        self.statusbar.setObjectName("statusbar")
        RSA.setStatusBar(self.statusbar)

        self.retranslateUi(RSA)
        QtCore.QMetaObject.connectSlotsByName(RSA)

    def retranslateUi(self, RSA):
        _translate = QtCore.QCoreApplication.translate
        RSA.setWindowTitle(_translate("RSA", "MainWindow"))
        self.groupBox.setTitle(_translate("RSA", "Prímszámok"))
        self.pPrime_Label.setText(_translate("RSA", "Adjon meg egy tetszőleges nagy \"p\" prímszámot!"))
        self.qPrime_Label.setText(_translate("RSA", "Adjon meg egy tetszőleges nagy \"q\" prímszámot!"))
        self.pInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pGenerate_Prime.setText(_translate("RSA", "Generálj!"))
        self.qGenerate_Prime.setText(_translate("RSA", "Generálj!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSA = QtWidgets.QMainWindow()
    ui = Ui_RSA()
    ui.setupUi(RSA)
    RSA.show()
    sys.exit(app.exec())
