# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from RSA_Values import Values
from RSA_Calc import Calculate
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_RSA(object):
    def initSubClasses(self):
        self.V = Values()
        self.C = Calculate()

    def setupUi(self, RSA):
        RSA.setObjectName("RSA")
        RSA.resize(631, 776)
        self.centralwidget = QtWidgets.QWidget(parent=RSA)
        self.centralwidget.setObjectName("centralwidget")
        self.primeNumbers_Box = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.primeNumbers_Box.setGeometry(QtCore.QRect(10, 0, 611, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.primeNumbers_Box.setFont(font)
        self.primeNumbers_Box.setObjectName("primeNumbers_Box")
        self.pPrime_Label = QtWidgets.QLabel(parent=self.primeNumbers_Box)
        self.pPrime_Label.setGeometry(QtCore.QRect(10, 40, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pPrime_Label.setFont(font)
        self.pPrime_Label.setObjectName("pPrime_Label")
        self.qPrime_Label = QtWidgets.QLabel(parent=self.primeNumbers_Box)
        self.qPrime_Label.setGeometry(QtCore.QRect(10, 100, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.qPrime_Label.setFont(font)
        self.qPrime_Label.setObjectName("qPrime_Label")
        self.pInput_Box = QtWidgets.QTextEdit(parent=self.primeNumbers_Box)
        self.pInput_Box.setGeometry(QtCore.QRect(350, 40, 151, 51))
        self.pInput_Box.setObjectName("pInput_Box")
        self.qInput_Box = QtWidgets.QTextEdit(parent=self.primeNumbers_Box)
        self.qInput_Box.setGeometry(QtCore.QRect(350, 100, 151, 51))
        self.qInput_Box.setObjectName("qInput_Box")
        self.pGenerate_Prime = QtWidgets.QPushButton(parent=self.primeNumbers_Box)
        self.pGenerate_Prime.setGeometry(QtCore.QRect(510, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pGenerate_Prime.setFont(font)
        self.pGenerate_Prime.setObjectName("pGenerate_Prime")
        self.qGenerate_Prime = QtWidgets.QPushButton(parent=self.primeNumbers_Box)
        self.qGenerate_Prime.setGeometry(QtCore.QRect(510, 100, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.qGenerate_Prime.setFont(font)
        self.qGenerate_Prime.setObjectName("qGenerate_Prime")
        self.keyGen_Box = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.keyGen_Box.setGeometry(QtCore.QRect(10, 170, 611, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.keyGen_Box.setFont(font)
        self.keyGen_Box.setObjectName("keyGen_Box")
        self.eLabel = QtWidgets.QLabel(parent=self.keyGen_Box)
        self.eLabel.setGeometry(QtCore.QRect(10, 40, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.eLabel.setFont(font)
        self.eLabel.setObjectName("eLabel")
        self.eInput_Box = QtWidgets.QTextEdit(parent=self.keyGen_Box)
        self.eInput_Box.setGeometry(QtCore.QRect(350, 40, 151, 51))
        self.eInput_Box.setObjectName("eInput_Box")
        self.eGenerate = QtWidgets.QPushButton(parent=self.keyGen_Box)
        self.eGenerate.setGeometry(QtCore.QRect(510, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.eGenerate.setFont(font)
        self.eGenerate.setObjectName("eGenerate")
        self.dLabel = QtWidgets.QLabel(parent=self.keyGen_Box)
        self.dLabel.setGeometry(QtCore.QRect(10, 100, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.dLabel.setFont(font)
        self.dLabel.setObjectName("dLabel")
        self.dInput_Box = QtWidgets.QTextEdit(parent=self.keyGen_Box)
        self.dInput_Box.setGeometry(QtCore.QRect(350, 100, 151, 51))
        self.dInput_Box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.dInput_Box.setReadOnly(True)
        self.dInput_Box.setObjectName("dInput_Box")
        self.messageBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(10, 340, 611, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.messageBox.setFont(font)
        self.messageBox.setObjectName("messageBox")
        self.mLabel = QtWidgets.QLabel(parent=self.messageBox)
        self.mLabel.setGeometry(QtCore.QRect(10, 40, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.mLabel.setFont(font)
        self.mLabel.setObjectName("mLabel")
        self.mInput_Box = QtWidgets.QTextEdit(parent=self.messageBox)
        self.mInput_Box.setGeometry(QtCore.QRect(350, 40, 251, 51))
        self.mInput_Box.setObjectName("mInput_Box")
        self.calculationBox = QtWidgets.QListWidget(parent=self.centralwidget)
        self.calculationBox.setGeometry(QtCore.QRect(10, 480, 611, 191))
        self.calculationBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.calculationBox.setObjectName("calculationBox")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(530, 680, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(430, 680, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.calculateButton.setFont(font)
        self.calculateButton.setObjectName("calculateButton")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 460, 611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        RSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 22))
        self.menubar.setObjectName("menubar")
        RSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RSA)
        self.statusbar.setObjectName("statusbar")
        RSA.setStatusBar(self.statusbar)

        self.retranslateUi(RSA)
        QtCore.QMetaObject.connectSlotsByName(RSA)

    def retranslateUi(self, RSA):
        _translate = QtCore.QCoreApplication.translate
        RSA.setWindowTitle(_translate("RSA", "MainWindow"))
        self.primeNumbers_Box.setTitle(_translate("RSA", "Prímszámok"))
        self.pPrime_Label.setText(_translate("RSA", "Adjon meg egy tetszőleges nagy \"p\" prímszámot!"))
        self.qPrime_Label.setText(_translate("RSA", "Adjon meg egy tetszőleges nagy \"q\" prímszámot!"))
        self.pInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pGenerate_Prime.setText(_translate("RSA", "Generálj!"))
        self.qGenerate_Prime.setText(_translate("RSA", "Generálj!"))
        self.keyGen_Box.setTitle(_translate("RSA", "Kulcsgenerálás"))
        self.eLabel.setText(_translate("RSA", "Adja meg az \"e\" publikus exponenst!"))
        self.eInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.eGenerate.setText(_translate("RSA", "Generálj!"))
        self.dLabel.setText(_translate("RSA", "A \"d\" privát exponens a következő:"))
        self.dInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.messageBox.setTitle(_translate("RSA", "Titkosítandó üzenet"))
        self.mLabel.setText(_translate("RSA", "Adja meg a titkosítandó \"m\" üzenetet! (Egész szám)"))
        self.mInput_Box.setHtml(_translate("RSA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "hr { height: 1px; border-width: 0; }\n"
                                                "li.unchecked::marker { content: \"\\2610\"; }\n"
                                                "li.checked::marker { content: \"\\2612\"; }\n"
                                                "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:700; font-style:normal;\">\n"
                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.exitButton.setText(_translate("RSA", "Kilépés"))
        self.calculateButton.setText(_translate("RSA", "Számolj!"))

    def showValues(self):
        self.C.storeValues(self.V,
                           self.pInput_Box.toPlainText(),
                           self.qInput_Box.toPlainText(),
                           self.eInput_Box.toPlainText(),
                           self.mInput_Box.toPlainText())
        element = self.C.calculate_RSA(self.V)
        result = QtWidgets.QListWidgetItem(element)
        self.calculationBox.clear()
        self.calculationBox.addItem(result)

    def configureButtons(self):
        self.exitButton.clicked.connect(app.quit)
        self.calculateButton.clicked.connect(self.showValues)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    RSA = QtWidgets.QMainWindow()
    ui = Ui_RSA()
    ui.initSubClasses()
    ui.setupUi(RSA)
    ui.configureButtons()
    RSA.show()
    sys.exit(app.exec())
